[package]
name = "password-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
directories = "5.0.1"
pgp = "0.10.1"
rand = "0.8.5"
smallvec = "1.11.0"
